repos:
- repo: https://github.com/pycqa/isort
  rev: 5.12.0  # isort版本号（可选）
  hooks:
    - id: isort
- repo: https://github.com/ambv/black
  rev: stable
  hooks:
    - id: black
      language_version: python3.9
#- repo: https://github.com/pre-commit/pre-commit-hooks
#  rev: v1.2.3
#  hooks:
#    - id: flake8
