repos:
- repo: https://github.com/pycqa/isort
  rev: 5.12.0  # isort版本号（可选）
  hooks:
    - id: isort
- repo: https://github.com/ambv/black
  rev: stable
  hooks:
    - id: black
      language_version: python3.9
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.910  # mypy版本号（可选）
  hooks:
    - id: mypy
      args: [--ignore-missing-imports, --strict-optional]  # 可选的mypy参数
      files: ^.*\.py$  # 要检查的文件类型正则表达式（可选）
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v1.2.3
  hooks:
    - id: flake8
